### ISSUE TITLE
Use less offensive splash screen image.

### ISSUE THREAD

**Issue by janArb** [huxi/lilith#11]
I want to promote lilith in my company, but don't think I can do that until the splash screen contains naked niples. Nice picture for private use, but it prevents from using lilith in professional environments...

**Comment by jeffjensen** [comment]
It is art, but it makes it difficult to suggest for use to my corporate customers and high school robotics team I mentor.

**Comment by ArawakCC** [comment]
Art or not, it's not appropriate for a North American corporate IT environment. Wouldn't be appropriate in India either. I can't use this at my work.

Is an artistic splash screen more important than adoption outside of Europe?

**Comment by huxi** [comment]
Related news story: [Italy covers up nude marble statues for Iranian president’s visit](https://www.washingtonpost.com/news/worldviews/wp/2016/01/26/italy-covers-up-nude-marble-statues-for-iranian-presidents-visit/)

**Comment by DanielGilbert** [comment]
> Is an artistic splash screen more important than adoption outside of Europe?

Yepp.

Wonder how the romans did survive with all this naked marble statues - gosh, they were even showing male genitals. :scream: 

At the end, this is Github: Create a fork, remove the picture, and handle the upstream changes. That's it.

**Comment by ceki** [comment]
@huxi In my opinion, liberty of expression is the liberty which sustains all the others. As such, I would encourage you to keep the splash screen as is. Moreover, you have presented options for disabling the splash.
