### ISSUE TITLE
Version 8.0.0 doesn't work with Ubuntu's OpenJDK 1.8.0_66-internal

### ISSUE THREAD

**Issue by HibikiTaisuna** [huxi/lilith#23]
There seems to be a bug with the versioncheck to start Lilith. I am using the newest version of OpenJDK8 (1.8.0_66-internal) and it is rejected as too old. Maybe the version check isn't correct.

As far as I can see every Ubuntu Wily based Distro currently uses the 1.8.0_66-internal version. It seems to be the most up to date version for Ubuntu 15.10 without adding additional PPAs. Lubuntu reports 1.8.0_66-internal-b17 as runtime environment and Xubuntu as well. Both using official Ubuntu repositories. Didn't test it with Fedora yet. Usually it should be enough to check for the version without the identifier and maybe adding a disclaimer that Beta or RC versions of Java aren't officially supported.

limux@xubuntu-vbox:~/Downloads$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

http://i.imgur.com/HSqrSo7.png

The provided 8.0.1 snapshot didn't fix this behavior.

**Comment by huxi** [comment]
I just uploaded another [SNAPSHOT](https://sourceforge.net/projects/lilith/files/lilith/8.0.1-SNAPSHOT/) that works for me in an Ubuntu Wily VirtualBox. I think I fumbled with the sulky snapshot dependencies the last time around.

Could you give it another try just to confirm?

**Comment by huxi** [comment]
Closing after >1 month of inactivity.
