### ISSUE TITLE
Lilith uses high performance graphics by default on MAC

### ISSUE THREAD

**Issue by jkolobok** [huxi/lilith#27]
By default Lilith requires hight performance graphics on mac and switches graphics card to discrete thus draining battery very quickly. 

![screen shot 2017-02-15 at 19 05 03](https://cloud.githubusercontent.com/assets/1977037/23002645/ac571518-f3b1-11e6-9339-a77685cad180.png)

solution:
Add  `NSSupportsAutomaticGraphicsSwitching`= 'YES

'
 to Info.plst  

```
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
```

![screen shot 2017-02-15 at 19 03 32](https://cloud.githubusercontent.com/assets/1977037/23002631/966bc938-f3b1-11e6-8808-ce20930573bd.png)

**Comment by huxi** [comment]
Thanks a lot for opening this issue and especially for the detailed explanation of the fix. I was entirely unaware of this problem and will fix it ASAP.

Would it be fine to thank you in the changelog?

**Comment by huxi** [comment]
I added a "thank you" to the changelog. Please holler if you'd like to have it removed.
