### ISSUE TITLE
Mac version doesn't launch is default java is 9

### ISSUE THREAD

**Issue by jkolobok** [huxi/lilith#31]
```
MBP:Java jkolobok$ open -a Lilith.app
LSOpenURLsWithRole() failed for the application /Applications/Lilith.app with error -10810.
```

**Comment by huxi** [comment]
Version 8.1.1 (the latest release version) works for me and uses Java 9 as expected.
Which version of Lilith did you try?

I also just updated the [macOS documentation](http://lilithapp.com/osx.html). I didn't realize that macOS Sierra yet again changed the way unsigned applications need to be manually accepted.

Chances are that you still need to jump through those hoops and that this is part of your problem.

**Comment by jkolobok** [comment]
8.1.1
I even redownloaded it and  tried enabling/disabling signature verification - the problem is the same. 
I'm using High Sierra, not Sierra.

**Comment by jkolobok** [comment]
Is there a way to change java version it will be using? Or can you create a build that would bundle java with it?

**Comment by huxi** [comment]
I can't check on High Sierra for now.

Can you try the documentation and see if that helps? Alternatively, you could try building from source and see if that works for you.

Follow the instructions in README.md. This should produce `lilith/build/distributions/de.huxhorn.lilith-8.2.0-SNAPSHOT-app.tgz` containing `Lilith.app`. You could also use one of the other Lilith versions, i.e. the ones that aren't wrapped in a `.app`.

I'll see what I can do regarding bundled Java version. Apple is making it increasingly hard writing software for macOS without paying them $99/year.

**Comment by huxi** [comment]
A coworker just checked Lilith 8.1.1 with Java 9-GA+181 on High Sierra and it works.

**Comment by jkolobok** [comment]
I don't know what was it, but it works now
